name: monorepo

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: ${{ env.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test --max-parallel=2

  deploy:

