name: monorepo

env:
  node-version: 18.x
  ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-versions: ${{ env.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test --max-parallel=2

  e2e:
    name: E2E on Chrome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5

        with:
          env: host=localhost,port=4200
          build: yarn build
          start: yarn run client
